Add ESLint, Prettier and linting git hook
aboutbits/pwa-boilerplate pull request #1
Opened 2021-03-12 15:05 UTC by NatanCieplinski

2021-03-15 16:24 UTC, mmalfertheiner requested changes

2021-03-15 16:24 UTC, mmalfertheiner commented on package.json
> +      "prettier",
I think this line can be removed, according to the docs: https://github.com/prettier/eslint-plugin-prettier#recommended-configuration

2021-03-15 17:42 UTC, NatanCieplinski commented on package.json
> +      "prettier",
In theory yes, in practice I did it and now i'm fighting with Prettier, that is not recognizing some allowed keywords

2021-03-15 17:49 UTC, mmalfertheiner commented on package.json
> +      "prettier",
Where does it happen for you? I tried it locally and it works just fine.

2021-03-15 17:51 UTC, mmalfertheiner commented on .prettierignore
> +out
Here I would only put:

```
build
node_modules
```
- We are not using yarn.
- out and .next are folders created by "Next.js"

2021-03-16 09:01 UTC, mmalfertheiner approved these changes

2021-03-16 14:13 UTC, merged